### ISSUE TITLE
gethostbyname Vulnerability? 

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/meterpreter#118]
http://www.openwall.com/lists/oss-security/2015/01/27/9

I don't think meterpreter is vulnerable as we use bionic?

**Comment by bcook-r7** [comment]
It's a 2 year old copy of bionic, and only on posix, but yeah, bionic cribs from various BSD sources.

In this case, it appears to be using netbsd's resolver.

**Comment by bcook-r7** [comment]
Thanks for checking in though!
