### ISSUE TITLE
Release notation

### ISSUE THREAD

**Issue by todb-r7** [rapid7/meterpreter#126]
I'd love to have some system/script that uses `git tag` to denote in the `meterpreter` repro what `meterpreter-bins` actually has. Otherwise, it's really easy to miss changes outside of @OJ blog posts.

For example, if I look at https://github.com/rapid7/metasploit-framework/pull/4743 , I do have a list of issues that were manually typed into the description, which is good. But, when I look at https://github.com/rapid7/meterpreter_bins/releases there were some manual release notes on v0.0.11, and no tags of note on https://github.com/rapid7/meterpreter/tags.

Any thoughts on that? I feel like this should be pretty automated and less mysterious about what's in what version of Meterpreter that's in Framework.

I did suggest something similiar for MDM (but there's no bin component there), on this comment: https://github.com/rapid7/metasploit-framework/pull/4741#issuecomment-73746719

**Comment by todb-r7** [comment]
IOW, I'd like to be able to query metasploit-framework's issue/PR logs, and get an idea of what other components are up to without having to do a lot of detective work. Would make things like talking about new features and bugs way easier to digest.

**Comment by bcook-r7** [comment]
Update on this, the new unified repo is now accessible: https://github.com/rapid7/metasploit-payloads

This includes a gem file as well as the source for all of the meterpreters in one place, so we should be able to track and tag changes fairly automatically (well, when we're fully migrated). I suspect we can even have the gem include the git commits in its changelog automatically.

I can refresh the unified repo as needed, so we're not in a super rush to cut over yet. Still working on the automation side of things.

**Comment by bcook-r7** [comment]
The new repo is live, and I added the first release tag - you can now checkout the 1.0.4 tag and get the source code for the 1.0.4 gem!
