### ISSUE TITLE
cleanup filesystem operations to be UTF-8 clean on the control channel, support unicode/native encoding on the OS side

### ISSUE THREAD

**Issue by bcook-r7** [rapid7/meterpreter#133]
We currently use the ASCII versions of file IO functions in meterpreter on Windows, which causes issues with different file encodings. We should do the conversion at the meterpreter side to whatever makes sense on the OS side, and pass UTF-8 encoding in the TLV messages to framework.

**Comment by OJ** [comment]
Moving over to UTF-8 for the whole lot of TLV values is definitely important. Not a small piece of work though!
