### ISSUE TITLE
Meterpreter build communicating to Kali repo framework

### ISSUE THREAD

**Issue by ghostop14** [rapid7/meterpreter#171]
Hey folks, I don't know if this is the right place to post a question but I've spent a solid week trying to compile the meterpreter git source and have it successfully show an active shell to a framework running on kali and it's starting but then dying.  I know there's a lot of broken frameworks after the dist-upgrade but I held mine back to the 4.11.2-2015051401 version and everything's functional.

I have a good bit of visual studio dev experience, and I've pulled the source code down and release builds compile fine (Win 7, latest SP and patches, VS 2013 for Desktops, etc. per the directions).  Of course my first test was just to git and compile and make sure I had working DLL's before making any changes.  When I swap in the newly built DLLs into the right directories and try to use them with a rev_http stager it does pull them and I see the first HTTP request and OK response in a wireshark capture but then it dies.  Putting the original DLLs that came with the framework back and the shell works fine again.  

Are there any compatibility issues with the git meterpreter source code and the framework version I'm running?  I would expect a git-and-build to produce DLLs that work okay with the framework?  Any help would be greatly appreciated.

Thanks!

**Comment by bcook-r7** [comment]
Hi @ghostop14 

You always need to use the very latest development version of metasploit-framework with the latest version of meterpreter, since there are ABI changes. You will need to either setup a development environment, or wait for the next Kali linux update, which should come this week, before it matches the latest version of meterpreter again. Thanks, and sorry for the confusion.

**Comment by ghostop14** [comment]
Thanks bcook-r7!  Sounds like that'll do it.  I'll sit tight.  Would it be possible to include another kali repo package for the snapshot of the meterpreter code that matches the framework version in the repo?  That might help with rebuild automation too as the updated frameworks come out and help me keep things in sync?

**Comment by bcook-r7** [comment]
As soon as we get everyone migrated to using the metasploit-payloads repo, we'll start tagging builds so it will be possible to align metasploit-framework releases to meterpreter source code.
