### ISSUE TITLE
Is it possible to make python plugin pre-loaded in Meterpreter session?

### ISSUE THREAD

**Issue by simonpunk** [rapid7/meterpreter#189]
As I start learning to make use of the python plugin and doing some testing on my VM. So I wonder if there is a faster way to skip the "load python" command at every time I get into the meterpreter session.

Thanks..

**Comment by OJ** [comment]
You can use stageless payloads and back the binary in, but you still need to `load python` to make MSF wire in the python commands. Why not just have an auto-run script on new sessions that does it for you?

**Comment by simonpunk** [comment]
Thanks, I end up with auto-run script....
