### ISSUE TITLE
Kiwi can't dump certs from non-default store

### ISSUE THREAD

**Issue by alx-k** [rapid7/meterpreter#191]
The default store is CURRENT_USER, I would like to export certs from LOCAL_MACHINE.

The argument parameter doesn't allow us to pass a target store argument:

```
mimikatz_command -f crypto::exportCertificates -a '\systemstore:LOCAL_MACHINE'
Emplacement : 'systemstore:LOCAL_MACHINE' introuvable !
```

I tried all combinations I can think of, nothing working.

**Comment by OJ** [comment]
To be clear, `mimikatz` != `kiwi`. There isn't currently an ability to use straight mimikatz commands using the `kiwi` extension.

The `kiwi` extension is out of date, and work is currently being done to bring it up to par with the current version of `mimikatz` that Ben has released. The current `mimikatz` extension in Meterpreter is intended for use with very old machines.

When the new version of `kiwi` is ready, this will be possible. Thanks!
