### ISSUE TITLE
Meterpreter session closed.  Reason: Died

### ISSUE THREAD

**Issue by kguddu007** [rapid7/meterpreter#200]
i am using reverse_tcp over  Internet using ngrok. i tried this in almost every ver. of android. it works just fine for lollipop and versions below lollipop but in  Marshmallow and nougat sessions are dieing. i tried it with embedding into other apk files. it was working for lollipop and below and Marshmallow and nougat were facing problems. 
Started reverse TCP handler on ::1:4444 
[*] Starting the payload handler...
[*] Sending stage (67614 bytes) to ::1
[*] Meterpreter session 20 opened (::1:4444 -> ::1:58208) at 2017-12-09 15:07:48 +0530
[*] Sending stage (67614 bytes) to ::1
[*] Meterpreter session 21 opened (::1:4444 -> ::1:58210) at 2017-12-09 15:07:48 +0530

meterpreter > [*] ::1 - Meterpreter session 20 closed.  Reason: Died

**Comment by anthonyisverycool** [comment]
Bro same with me .help me too
