### ISSUE TITLE
Unable to exit powershell from a meterpreter session

### ISSUE THREAD

**Issue by bgdrbell** [rapid7/meterpreter#203]
Everytime I start a new meterpreter session it takes me straight to the powershell command mode. when I type exit, it completely closes out my session. commands work while in shell mode but I want to get back to meterpreter mode. not sure how how to fix this...

![image](https://user-images.githubusercontent.com/31639688/35366064-74bf8764-0145-11e8-88d1-7017a6da9ed5.png)

**Comment by bgdrbell** [comment]
ok, a second restart of of the Kali vm solved the problem.

**Comment by bcoles** [comment]
That's not a meterpreter session. It's a shell session. `exit` and `^C` exits a shell.
