### ISSUE TITLE
Multiple Sessions Kills previous

### ISSUE THREAD

**Issue by amiralkizaru** [rapid7/meterpreter#205]
Hello guys 
I want to know if there's an options in "show advanced" I can use to prevent my first session from dying if another sessions get's opened

**Comment by busterb** [comment]
Are you the guy who hung out for 20 minutes and disappeared on IRC? There's not enough information here to know what problem you're actually having.

**Comment by busterb** [comment]
It sounds like maybe you have a misconfiguration, or are encountering a bug. There is no option to my knowledge for setting the maximum number of sessions that can be connected. It is possible you have a limited number of ports available, e.g. if you're trying to connect multiple sessions via the 'bind' method.

**Comment by amiralkizaru** [comment]
No the thing is when I sent Payload to victim machine and the payload is clicked I get Meterpreter session 
But if the payloads is clicked more than once it create a lot of sessions that kills the previous one's 
I want to know if there's is a method or an option that I can activate to keep just the first and If the payloads is clicked more than once the other session will be on background or smthing like that
I hope i'm clear x)

**Comment by busterb** [comment]
You're not really showing me what you're doing, so I'll try to guess.
Did you set 'ExitOnSession' to false?
Are you running your handler as a background job? `run -j` ?

**Comment by amiralkizaru** [comment]
No I didnt I think that what I was looking for that ' ExitOnSession' to false 
It will prevent my first session from dying even If the victim clicks more than once

**Comment by timwr** [comment]
I presume you're using Android?
Have you tried the `AndroidWakelock` and `AndroidHideAppIcon` options?

**Comment by timwr** [comment]
Stay on IRC and we'll try help you out.
