### ISSUE TITLE
meterpreter problem

### ISSUE THREAD

**Issue by sindikto** [rapid7/meterpreter#207]
Hi, good day. i've a problem and and I do not know what I can do.

355/5000
and I do not know what I can do
I've been a long time getting a connection
meterpreter using rubber duky, and now that I've
come to get (metasploit says:
[*] Started reverse TCP handler on 192.168.1.70:1315 
[*] Sending stage (179779 bytes) to 192.168.1.10
[*] Meterpreter session 1 opened (192.168.1.70:1315 -> 192.168.1.10:49840) at 2019-05-20 17:37:44 +0200
? ? ? ? meterpreter >not appears
but it does not come out it does not appear at the meterpreter prompt that
would allow me to enter the other commands of
meterpreter Something escapes me? Any suggestions?

**Comment by bcoles** [comment]
You can list available sessions with `sessions -l`

You can interact with a session using `sessiond -i <id>`, for example, `sessiond -i 1`

**Comment by sindikto** [comment]
Thanks too much for your time and interes, but all I writte is nothing, metasploit 
no see my commands because there is not promp

> sessions -l

thankstoo much for your time and interes but wen I put  sessions -l notning sucded  nothing because no prompt   t's like throwing commands into the air thanks very much anyway

**Comment by bcoles** [comment]
It's possible that the module has not finished. Try `ctrl` + `c`, then `sessions -l`.

If that doesn't work, we would need to see the full terminal output to have a better understanding of what you're experiencing.

**Comment by sindikto** [comment]
![Captura de NOPRPMPT de 2019-05-20 19-34-11](https://user-images.githubusercontent.com/45392727/58040900-fb88ae80-7b36-11e9-9912-70f4c1628b90.png)

**Comment by bcoles** [comment]
Try `ctrl+c` then `sessions -l`

**Comment by sindikto** [comment]
Thanks too much for your time and interes, but all I writte is nothing, metasploit 
no see my commands because there is not promp
![Captura de pantalla de 2019-05-20 19-43-45](https://user-images.githubusercontent.com/45392727/58041300-0e4fb300-7b38-11e9-92bd-efb65f47b8a7.png)

**Comment by bcoles** [comment]
I see a `meterpreter >` prompt. It's right there ^, where it says `meterpreter >`.

**Comment by sindikto** [comment]
it seemed to me that everything was ok but
I'm trying and it's not going
conffirmed no work ok

**Comment by sindikto** [comment]
![Captura de pantalla de 2019-05-20 19-54-20](https://user-images.githubusercontent.com/45392727/58042136-245e7300-7b3a-11e9-9ebb-b5f35a0f60f2.png)

**Comment by sindikto** [comment]
Thanks too much for your time and interes, but all I writte is nothing, metasploit 
no see my commands because there is not promp
![Uploading Captura de pantalla de 2019-05-20 19-43-45.png…]()

**Comment by sindikto** [comment]
Now I think the problem is with the file inject.bin that opens the connection with some problem and then meteprepreer does not work. I say this as I have an * .exe made with msfvenom and open the connection with the metasploit listener perfectly. Something very interesting would be to get it executed it with RD.
Thank you very much for your time.
