### ISSUE TITLE
where does meterpreter save the dump_sms things what is the directory

### ISSUE THREAD

**Issue by soulzzcs** [rapid7/meterpreter#208]
i couldnt find them so if someone can help me?

**Comment by bcoles** [comment]
I'm not sure that it does, unless you specify the `-o` flag with a `path`.

https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/post/meterpreter/ui/console/command_dispatcher/android.rb#L189

It should tell you where the data is saved:

```ruby
      when '-o'
        path = val

      # ...

      ::File.write(path, data)
      print_status("SMS #{sms_list.count == 1 ? 'message' : 'messages'} saved to: #{path}")
```

**Comment by timwr** [comment]
`meterpreter > lpwd` will show you the path where the file is saved.
