### ISSUE TITLE
Could not execute vnc

### ISSUE THREAD

**Issue by Huibuh2010** [rapid7/meterpreter#214]
Hey Hey,

if i run in a meterpreter session "run vnc" an error comes up

Could not execute vnc: ArgumentError wrong number of arguments (given 2, expected 0..1)

anybody a idea?

thx

**Comment by bcoles** [comment]
Scripts are no longer supported.

Also, there's a PR pending to fix scripts:

https://github.com/rapid7/metasploit-framework/pull/15542

**Comment by bcoles** [comment]
#15562
